import Head from 'next/head'
import('amfe-flexible')

export default function MyHead() {
    return (
        <div>
            <Head>
                <meta name="renderer" content="webkit" />
                <title>title</title>
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"></meta>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

        </div>)
}